routes/web.php
     * Purpose: create segments , list segments , export excel and change segment type status
     * Created Date: 27/02/2020
     */
    Route::group(['namespace' => 'notification', 'prefix' => 'notification', 'as' => 'notification.'], function () {
        Route::group(['prefix' => 'manage-segments', 'as' => 'manage-segments.'], function () {
            Route::get('/', 'ManageSegmentsController@index')->name('index');
            Route::post('/', 'ManageSegmentsController@search')->name('search');
            Route::get('createSegments', 'ManageSegmentsController@createSegments')->name('createSegments');
            Route::post('insertCreateSegments', 'ManageSegmentsController@insertCreateSegments')->name('insertCreateSegments');
            Route::post('manageSegmentsChangeStatus', 'ManageSegmentsController@manageSegmentsChangeStatus')->name('manageSegmentsChangeStatus');
            Route::get('exportExcel/{SEGMENT_ID}', 'ManageSegmentsController@exportExcel')->name('exportExcel');
            Route::post('chaakeSegmentTitle', 'ManageSegmentsController@chaakeSegmentTitle')->name('chaakeSegmentTitle');
            Route::POST('SegmentMatchExcel', 'ManageSegmentsController@SegmentMatchExcel')->name('SegmentMatchExcel');
        });

        /**
         * Author: Hitesh Aloney
         * Purpose: All push notification related routes.
         * Created Date: 04/03/2020
         */
        Route::group(['prefix' => 'push-notification', 'as' => 'push-notification.'], function () {
            Route::match(['get', 'post'], '/', "ManagePushNotificationController@index")->name('index');
            Route::get('/create', 'ManagePushNotificationController@create')->name('create');
            Route::post('/review-excel', 'ManagePushNotificationController@reviewExcel')->name('review-excel');
            Route::post('/store', 'ManagePushNotificationController@store')->name('store');
            Route::get('/{id}/edit', 'ManagePushNotificationController@edit')->name('edit');
            Route::get('/{id}/show', "ManagePushNotificationController@show")->name('show');
            Route::get('exportExcel/{id}/{seg_id?}', "ManagePushNotificationController@exportExcel")->name('exportExcel');
        });
    });

    /**
     * Author: Kamlesh Kumar
     * Purpose: All Pay By Cash And NEFT Releted Route.
     * Created Date: 18/02/2020
     */
    Route::group(['namespace'=>'transaction', 'prefix'=>'transaction', 'as'=>'transaction.'], function(){
        Route::group(['prefix'=>'paybycashneft', 'as'=>'paybycashneft.'], function(){
            Route::get('/', 'PayByCashNeft@index')->name('index');
            Route::post('checkUserDepositBalance','PayByCashNeft@checkUserDepositBalance')->name('checkUserDepositBalance');
            Route::post('createPayByCash','PayByCashNeft@createPayByCash')->name('createPayByCash');
            Route::post('paybycashneftexcel','PayByCashNeft@paybycashneftexcel')->name('paybycashneftexcel');
            Route::post('insertpaybycashneftexcel','PayByCashNeft@insertpaybycashneftexcel')->name('insertpaybycashneftexcel');
        });
    });


    Route::group(['namespace'=>'baazirewards', 'prefix'=>'baazirewards', 'as'=>'baazirewards.'], function(){
        Route::group(['prefix'=>'cashback-levels', 'as'=>'cashback-levels.'], function(){
            Route::get('/', 'CashbackLevelsController@index')->name('index');
            Route::post('insertCashbackLevel', 'CashbackLevelsController@insertCashbackLevel')->name('insertCashbackLevel');
            Route::post('UpdateCashbackLevel', 'CashbackLevelsController@UpdateCashbackLevel')->name('UpdateCashbackLevel');
        });
    });

    /**
     * Author: Hitesh Aloney
     * Purpose: All Leaderboard related routes.
     * Created Date: 18/03/2020
     */
    Route::group(['namespace'=>'leaderboard', 'prefix'=>'leaderboard', 'as'=>'leaderboard.'], function(){
        Route::group(['prefix'=>'manage-leaderboard','as'=>'manage-leaderboard.'], function(){
           Route::get('/','ManageLeaderboardController@index')->name('index');
           Route::post('/search','ManageLeaderboardController@search')->name('search');
           Route::get('/create','ManageLeaderboardController@create')->name('create');
           Route::get('/{id}/{action}','ManageLeaderboardController@edit')->name('edit');
           Route::post('/','ManageLeaderboardController@store')->name('store');
           Route::patch('/{id}','ManageLeaderboardController@update')->name('update');
           Route::get('/{id}','ManageLeaderboardController@show')->name('show');
        });

        Route::group(['prefix'=>'manage-mapping','as'=>'manage-mapping.'], function(){
           Route::get('/','ManageMappingController@index')->name('index');
           Route::post('/','ManageMappingController@store')->name('store');
           Route::delete('/{id}','ManageMappingController@destroy')->name('destroy');
           Route::post('/search','ManageMappingController@search')->name('search');
        });

    });

    /**
     * Author: Kamlesh Kumar
     * Purpose: All Responsible Gaming Releted Routes
     * Created Date: 16/04/2020
     */
    Route::group(['namespace'=>'responsiblegaming', 'prefix'=>'responsiblegaming', 'as'=>'responsiblegaming.'], function(){
        Route::group(['prefix'=>'pokerbreak', 'as'=>'pokerbreak.'], function(){
            Route::match(['get','post'],'/','ResponsibleGamingController@index')->name('pokerbreak');
            Route::post('/show','ResponsibleGamingController@show')->name('show');
            Route::post('/updatePokerBreak','ResponsibleGamingController@update')->name('updatePokerBreak');
            Route::get('/getExcelExport', 'ResponsibleGamingController@excelExportforPokerBreak')->name('getExcelExport');
        });
        Route::match(['get','post'],'/showAllLogs','ResponsibleGamingController@showAllLogs')->name('showalllogs');
        Route::match(['get','post'],'/addusername','ResponsibleGamingController@addusername')->name('adduser');
        Route::match(['get','post'],'/ofclimit','ResponsibleGamingController@ofclimit')->name('ofclimit');
        Route::post('showofctable','ResponsibleGamingController@showofctable')->name('showofctable');
        Route::post('/updateofclimit','ResponsibleGamingController@updateofclimit')->name('updateofclimit');
        Route::match(['get','post'],'/cashtablelimit','ResponsibleGamingController@cashtablelimit')->name('cashtablelimit');
        Route::post('showcashtable','ResponsibleGamingController@showcashtable')->name('showcashtablemodel');
        Route::post('/updatecashlimit','ResponsibleGamingController@updatecashlimit')->name('updatecashlimit');
        Route::match(['get','post'],'/allrequest','ResponsibleGamingController@allrequest')->name('allrequest');
        Route::get('/getExcelExport', 'ResponsibleGamingController@excelExport')->name('getExcelExport');
        Route::post('/updaterequest','ResponsibleGamingController@updaterequest')->name('updaterequest');
        Route::group(['prefix'=>'depositlimit', 'as'=>'depositlimit.'], function(){
            Route::get('edit/{user_id}', 'DepositLimitController@index')->name('editDepositLimit');
            Route::post('update/{user_id}', 'DepositLimitController@store')->name('updateDepositLimit');
        });

    });

    Route::group(['namespace' => 'staticblockmodule', 'prefix' => 'staticblockmodule', 'as' => 'staticblockmodule.'], function () {
        /**
         * Author: Nitesh Kumar Jha
         * Purpose: Get all website management related static block module url
         * Created Date: 09-09-2020
         */
        Route::group(['prefix'=>'staticblock', 'as'=>'staticblock.'], function(){
            Route::get('/', 'StaticblockController@index')->name('index');
            Route::post('insertStaticblock', 'StaticblockController@insertStaticblock')->name('insertStaticblock');
            Route::post('checkStaticBlockTitle', 'StaticblockController@checkStaticBlockTitle')->name('checkStaticBlockTitle');
            Route::get('search', 'StaticblockController@StaticblockList')->name('StaticblockList');
            Route::post('search', 'StaticblockController@searchResult')->name('search_post');
            Route::get('editStaticBlock/{STATIC_BLOCK_ID}', 'StaticblockController@editStaticBlock')->name('editStaticBlock');
            Route::post('updateStaticBlock/{STATIC_BLOCK_ID}', 'StaticblockController@updateStaticBlock')->name('updateStaticBlock');

        });
    });

    Route::group(['namespace'=>'contest', 'prefix'=>'contest', 'as'=>'contest.'], function(){
        Route::group(['prefix'=>'ticket-ledgers', 'as'=>'ticket-ledgers.'], function(){
            Route::get('/', 'TicketLedgerController@index')->name('index');
            Route::post('/', 'TicketLedgerController@TicketLedgerSearch')->name('TicketLedgerSearch');
            Route::get('exportExcel','TicketLedgerController@exportExcel')->name('exportExcel');
        });
    });
});

Route::group(['middleware' => ['web', 'checkserverip']], function () {
    Route::get('/mailxls/{days?}', 'bo\marketing\CohortReportController@scheduleCRONmailCohortReport')->where('days', '[0-9]+')->name('mailxls');
    Route::get('cron-mail-pb-stats-report', 'bo\reports\PBDailyReportController@index')->name('cron-mail-pb-stats-report');
    Route::get('newtest-mail-pb-stats-report', 'bo\reports\TestPBDailyReportController@index')->name('newtest-mail-pb-stats-report'); // for testing pb-daily-stats
    Route::get('PB-LP-REGISTRATION', 'bo\reports\LandingPageReportAutomationController@index')->name('PB-LP-REGISTRATION');
    Route::get('PB-LP-FTD', 'bo\reports\LandingPageReportAutomationController@pbLFTD')->name('PB-LP-FTD');
    Route::get('PB-LP-REVENUE', 'bo\reports\LandingPageReportAutomationController@pbLPREVENUE')->name('PB-LP-REVENUE');
    Route::get('weekly-performance-report', 'bo\reports\WeeklyPerformanceReportAutomationController@index')->name('weekly-performance-report');

app/Http/Controllers/bo/baazirewards/CashbackLevelsController.php
<?php

namespace App\Http\Controllers\bo\baazirewards;

use Illuminate\Http\Request;
use App\Http\Controllers\bo\BaseController;
use App\Models\RewardCashbackLevel;
use Auth;
use App\Facades\PokerBaazi;



/**
 * Author: Nitesh Kumar Jha
 * Purpose:  Insert and update Reward CashbackLevel 
 * Created Date: 24-3-2020
 * modify date: 25-9-2020
 */

class CashbackLevelsController extends BaseController
{
    //
    public function index()
    {  
        $RewardCashbackLevelResult = RewardCashbackLevel::select('LEVEL_ID', 'MIN_REWARD_POINTS','MAX_REWARD_POINTS','CASHBACK_AMOUNT')
            ->orderBy('LEVEL_ID', 'DESC')
            ->get();
       return view('bo.views.cashbacklevels.index',['RewardCashbackLevelResult' => $RewardCashbackLevelResult]);
    }

    public function insertCashbackLevel(Request $request)
    {
     
        request()->page;
        $request->validate([
            "MIN_REWARD_POINTS" => 'required',
            "MAX_REWARD_POINTS" => 'required',
            "CASHBACK_AMOUNT" =>'required',
        ]);

        $insert = [
            'MIN_REWARD_POINTS' => $request->MIN_REWARD_POINTS,
            'MAX_REWARD_POINTS' => $request->MAX_REWARD_POINTS,
            'CASHBACK_AMOUNT' =>  $request->CASHBACK_AMOUNT
        ];
        
        $data = RewardCashbackLevel::insert($insert);
                //Start user Activity Tracking 
                $activity = [
                    'admin' => Auth::user()->id,
                    'module_id' => 70,
                    'action' => "Add Cashback levels",
                    'data' => json_encode($insert)
                ];
                PokerBaazi::storeActivity($activity);
                if ($data == 1) {
                    return redirect()->back()->with('success', "Insert Data Successfully");
                } else {
                    return redirect()->back()->with('error', "Insert Data Failed.");
                }
               
    }


    public function UpdateCashbackLevel(Request $request)
    {
     
        request()->page;
        $request->validate([
            "MIN_REWARD_POINTS" => 'required',
            "MAX_REWARD_POINTS" => 'required',
            "CASHBACK_AMOUNT" => 'required',
            "LEVEL_ID" => 'required',
        ]);
       
        $update = [
            'MIN_REWARD_POINTS' => $request->MIN_REWARD_POINTS,
            'MAX_REWARD_POINTS' => $request->MAX_REWARD_POINTS,
            'CASHBACK_AMOUNT' =>  $request->CASHBACK_AMOUNT
        ];
       
        $data = RewardCashbackLevel::where('LEVEL_ID', $request->LEVEL_ID)
        ->update($update);
                //Start user Activity Tracking 
                $activity = [
                    'admin' => Auth::user()->id,
                    'module_id' => 70,
                    'action' => "Update Cashback levels",
                    'data' => json_encode($update)
                ];
                PokerBaazi::storeActivity($activity);
                if ($data == 1) {
                    return redirect()->back()->with('success', "Update Successfully");
                } else {
                    return redirect()->back()->with('error', "Update Failed.");
                }
               
                
    }


}

resources/views/bo/views/cashbacklevels/index.blade.php
@extends('bo.layouts.master')

@section('title', "Cashback Levels | PB BO")

@section('pre_css')

@endsection

@section('post_css')

@endsection

@section('content')
<div class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="page-title-box">
               <div class="page-title-right">
                  <ol class="breadcrumb m-0">
                     <li class="breadcrumb-item"><a>Baazi Rewards</a></li>
                     <li class="breadcrumb-item active"> Cashback Levels</li>
                  </ol>
               </div>
               <h4 class="page-title">
                  Cashback Levels
               </h4>
            </div>
         </div>
      </div>
      <!-- end col -->
   </div>
   <div class="row">
      <div class="col-12">
         <div class="card">
            <div class="card-body">
               <div class="row mb-1">
                  <div class="col-lg-8">
                     <h5 class="font-18">Manage Cashback Levels</h5>
                  </div>
                  <div class="col-lg-4 mb-2">
                     <div class="text-lg-right mt-lg-0"><a href="#" data-toggle="modal" data-target="#addModel" class="btn btn-success waves-effect waves-light"><i class="fa fa-plus mr-1"></i> Create Level</a></div>
                  </div>
               </div>
               <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                  <thead>
                     <tr>
                        <th>Level #</th>
                        <th>Min Reward Point</th>
                        <th>Max Reward Point</th>
                        <th>Cashback Amount</th>
                        <th>Action</th>
                     </tr>
                  </thead>
                  <tbody>
                     @foreach ($RewardCashbackLevelResult as $key => $result)
                     <tr>
                        <td>{{ $result->LEVEL_ID }} </td>
                        <td>{{ $result->MIN_REWARD_POINTS }} </td>
                        <td>{{ $result->MAX_REWARD_POINTS }} </td>
                        <td>{{ $result->CASHBACK_AMOUNT }} </td>
                        <td>
                           <a class="action-icon font-14 tooltips" href="#" data-toggle="modal" data-target="#editModel_{{ $result->LEVEL_ID }}">
                              <i class="fa fa-edit"></i><span class="tooltiptext">Edit</span>
                           </a>

                           <div class="modal fade" id="editModel_{{ $result->LEVEL_ID }}">
                              <div class="modal-dialog ">
                                 <div class="modal-content bg-transparent shadow-none">
                                    <div class="card">
                                       <div class="card-header bg-dark py-3 text-white">
                                          <div class="card-widgets">
                                             <a href="#" data-dismiss="modal">
                                                <i class="mdi mdi-close"></i>
                                             </a>
                                          </div>
                                          <h5 class="card-title mb-0 text-white font-18">Edit Cashback Levels</h5>
                                       </div>
                                       <form id="EditCashbackLevel" data-default-url="{{route('baazirewards.cashback-levels.UpdateCashbackLevel')}}" action="{{route('baazirewards.cashback-levels.UpdateCashbackLevel')}}" method="post">
                                          @csrf
                                          <div class="card-body">
                                             <input type="hidden" class="form-control" name="LEVEL_ID" id="LEVEL_ID" placeholder="Level" value="{{ $result->LEVEL_ID }}">
                                             <div class="form-group">
                                                <label>Min Reward Point: <span class="text-danger">*</span></label>
                                                <input type="number" class="form-control" name="MIN_REWARD_POINTS" id="MIN_REWARD_POINTS" placeholder="Min Reward Points" value="{{ $result->MIN_REWARD_POINTS }}" step='0.01'  min="1" required="">
                                             </div>
                                             <div class="form-group mb-3">
                                                <label>Max Reward Point: <span class="text-danger">*</span></label>
                                                <input type="number" class="form-control" name="MAX_REWARD_POINTS" id="MAX_REWARD_POINTS" placeholder="Max Reward Points" value="{{ $result->MAX_REWARD_POINTS }}" step='0.01' min="1" required="">
                                             </div>
                                             <div class="form-group mb-3">
                                                <label>Cashback Amount: <span class="text-danger">*</span></label>
                                                <input type="number" class="form-control" name="CASHBACK_AMOUNT" id="CASHBACK_AMOUNT" placeholder="Cashback amount" value="{{ $result->CASHBACK_AMOUNT }}" step='0.01' min="1" required="">
                                             </div>
                                             <button type="submit" name="Update" id="Update" class="btn btn-warning waves-effect waves-light mr-1 formActionButton"><i class="far fa-edit  mr-1"></i> Update</button>
                                             <button style="display:none" class="btn btn-primary formActionButton mr-1" type="button" disabled>
                                                <span class="spinner-border spinner-border-sm mr-1" role="status" aria-hidden="true"></span>
                                                Loading...
                                             </button>
                                             <button type="reset" id="resetModel" class="btn btn-secondary waves-effect waves-light"><i class="fas fa-eraser mr-1"></i> Clear</button>
                                          </div>
                                       </form>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </td>
                     </tr>
                     @endforeach
                  </tbody>
               </table>
               <div class="customPaginationRender mt-2" data-form-id="#userSearchForm" class="mt-2">
                  <div>More Records</div>
                  <div>
                  </div>
               </div>
            </div>
            <!-- end card body-->
            <!-- end card -->
         </div>
         <!-- end col-->
      </div>
   </div>
</div>
</div>
<div class="modal fade" id="addModel">
   <div class="modal-dialog ">
      <div class="modal-content bg-transparent shadow-none">
         <div class="card">
            <div class="card-header bg-dark py-3 text-white">
               <div class="card-widgets">
                  <a href="#" data-dismiss="modal">
                     <i class="mdi mdi-close"></i>
                  </a>
               </div>
               <h5 class="card-title mb-0 text-white font-18">Add Cashback Levels</h5>
            </div>
            <form id="AddCashbackLevel" data-default-url="{{route('baazirewards.cashback-levels.insertCashbackLevel')}}" action="{{route('baazirewards.cashback-levels.insertCashbackLevel')}}" method="post">
               @csrf
               <div class="card-body">
                  <div class="form-group">
                     <label>Min Reward Point: <span class="text-danger">*</span></label>
                     <input type="number" class="form-control" name="MIN_REWARD_POINTS" id="MIN_REWARD_POINTS" placeholder="Min Reward Points" value="" required="" step='0.01' min="1">
                  </div>
                  <div class="form-group mb-3">
                     <label>Max Reward Point: <span class="text-danger">*</span></label>
                     <input type="number" class="form-control" name="MAX_REWARD_POINTS" id="MAX_REWARD_POINTS" placeholder="Max Reward Points" value="" required="" step='0.01' min="1">
                  </div>
                  <div class="form-group mb-3">
                     <label>Cashback Amount: <span class="text-danger">*</span></label>
                     <input type="number" class="form-control" name="CASHBACK_AMOUNT" id="CASHBACK_AMOUNT" placeholder="Cashback amount" value="" required="" step='0.01' min="1">
                  </div>
                  <button type="submit" name="confirmExcelUpload" id="confirmExcelUpload" class="btn btn-success waves-effect waves-light formActionButtonvv"><i class="fa fa-save mr-1"></i> Save</button>
                  <button style="display:none" class="btn btn-primary formActionButtonvv mr-1" type="button" disabled>
                     <span class="spinner-border spinner-border-sm mr-1" role="status" aria-hidden="true"></span>
                     Loading...
                  </button>
                  <button type="reset" id="reset" class="btn btn-secondary waves-effect waves-light"><i class="fas fa-eraser mr-1"></i> Clear</button>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
@endsection

@section('js')
<script>
   $(document).ready(function() {
      $("#reset").click(function() {
         trigger("reset");
      });

      $("#resetModel").click(function() {
         trigger("reset");
      });

      $("#EditCashbackLevel").validate({

      });

      $('#Update').on('click', (e) => {
         if ($("#EditCashbackLevel").valid()) {
            $('.formActionButton').toggle();
            $('#Update').hide();
         }
      });

      $('#confirmExcelUpload').on('click', (e) => {
         if ($("#AddCashbackLevel").valid()) {
            $('.formActionButtonvv').toggle();
            $('#confirmExcelUpload').hide();
         }
      });
   })
</script>
@endsection
@section('post_js')
@endsection