routes/web.php
			Route::post('editcampaign', 'ManageCampaignController@updateCampaign');
			Route::get('viewuserexcel/{id}', 'ManageCampaignController@viewUserExcel')->name('viewuserexcel');
			Route::post('getCampaignURL', 'ManageCampaignController@getCampaignURL');
			Route::post('editDataExcel', 'ManageCampaignController@editDataExcel');
			Route::post('updateDataExcel', 'ManageCampaignController@updateDataExcel');
			Route::post('deleteDataExcel', 'ManageCampaignController@deleteDataExcel');
			Route::post('addViewUserExcel', 'ManageCampaignController@addViewUserExcel');
			Route::get('viewbulkcode/{id}', 'ManageCampaignController@viewbulkcode')->name('viewbulkcode');
			Route::post('changeCampaignStatus', 'ManageCampaignController@changeCampaignStatus');
			Route::get('viewcontactexcel/{id}', 'ManageCampaignController@viewContactExcel')->name('viewcontactexcel');
			Route::post('editDataExcelContact', 'ManageCampaignController@editDataExcelContact');
			Route::post('updateDataExcelContact', 'ManageCampaignController@updateDataExcelContact');
			Route::post('deleteDataExcelContact', 'ManageCampaignController@deleteDataExcelContact');
			Route::post('addViewUserExcelContact', 'ManageCampaignController@addViewUserExcelContact');
			Route::post('deleteDataPromoCampaign', 'ManageCampaignController@deleteDataPromoCampaign');
			Route::post('chkUserValid', 'ManageCampaignController@chkUserValid');
			Route::post('chkUsersExcelValid', 'ManageCampaignController@chkUsersExcelValid');
			Route::post('chkExcelValidContact', 'ManageCampaignController@chkExcelValidContact');
		});
    });

    /**
     * Setting Routes
     * Including Menu, Modules
     */
    Route::group(['namespace' => 'settings', 'prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::group(['prefix' => 'menu', 'as' => 'menu.', 'middleware' => 'canAccess:view,menu'], function () {
            Route::get('/', 'MenuController@index')->name('index');
            Route::middleware('canAccess:edit,menu')->post('/order', 'MenuController@order')->name('order');
            Route::middleware('canAccess:edit,menu')->post('/store/{id?}', 'MenuController@store')->name('store');
        });

        Route::group(['prefix' => 'module', 'as' => 'module.', 'middleware' => 'canAccess:view,module'], function () {
            Route::get('/', 'ModuleController@index')->name('index');
            Route::middleware('canAccess:edit,module')->post('/store/{id?}', 'ModuleController@store')->name('store');
        });

        /**
         * @author Nitesh Sharma
         * Bannner Routes
         */
        Route::group(['prefix' => 'banner', 'as' => 'banner.'], function () {
            Route::get('/', 'ManegeBannerController@index')->name('index');
            Route::get('managebanner', 'ManegeBannerController@managebanner')->name('managebanner');
            Route::post('insertbanner', 'ManegeBannerController@insertbanner')->name('insertbanner');
            Route::get('editappbanner/{APP_BANNER_ID}', 'ManegeBannerController@editappbanner')->name('editappbanner');
            Route::post('updateAppBanner/{APP_BANNER_ID}', 'ManegeBannerController@updateAppBanner')->name('updateAppBanner');
            Route::post('bannerChangeStatus', 'ManegeBannerController@bannerChangeStatus')->name('bannerChangeStatus');
        });

        /**
         * Author: Hitesh Aloney
         * Reason Routes
         */
        Route::group(['prefix' => 'reason-action', 'as' => 'reason-action.'], function () {
            Route::get('/', 'reason\ManageReasonController@index')->name('index');
            Route::get('/{id}', 'reason\ManageReasonController@show')->name('show');
            Route::patch('/{id}', 'reason\ManageReasonController@update')->name('update');
            Route::post('/', 'reason\ManageReasonController@store')->name('store');
        });

        Route::group(['prefix' => 'reason-category', 'as' => 'reason-category.'], function () {
            Route::get('/', 'reason\ManageReasonCategoryController@index')->name('index');
            Route::get('/{id}', 'reason\ManageReasonCategoryController@show')->name('show');
            Route::patch('/{id}', 'reason\ManageReasonCategoryController@update')->name('update');
            Route::post('/', 'reason\ManageReasonCategoryController@store')->name('store');
        });
    });

    /**
     * Live Tournament Routes
     */
    Route::group(['namespace' => 'livetournament', 'prefix' => 'livetournament', 'as' => 'livetournament.'], function () {
        Route::group(['prefix' => 'tournament', 'as' => 'tournament.'], function () {
            Route::get('search', 'LiveTournamentController@index')->name('index');
            Route::post('search', 'LiveTournamentController@searchResult')->name('search_post');
            Route::get('liveTournamentDetails/{TOURNAMENT_ID}', 'LiveTournamentController@liveTournamentDetails')->name('liveTournamentDetails');
            Route::get('lateregistrationClosed/{TOURNAMENT_ID}', 'LiveTournamentController@lateregistrationClosed')->name('lateregistrationClosed');
            Route::get('updateRebuy/{tid}/{id}', 'LiveTournamentController@updateRebuy')->name('updateRebuy');
            Route::get('updateUnRegistration/{tid}/{id}', 'LiveTournamentController@updateUnRegistration')->name('updateUnRegistration');
            Route::post('updateAssignTable', 'LiveTournamentController@updateAssignTable')->name('updateAssignTable');
            Route::get('exportExcel', 'LiveTournamentController@exportExcel')->name('exportExcel');
        });

        #Live Entries
        Route::group(['prefix' => 'live-entries', 'as' => 'live_entries.'], function () {
            Route::get('/', 'LiveTournamentEntriesController@index')->name('index');
            Route::post('/', 'LiveTournamentEntriesController@store')->name('store');
            Route::post('ajax-live-entries-getuser', 'LiveTournamentEntriesController@ajaxGetUserStatus')->name('ajaxGetUserStatus');
        });
    });

    /**
     * Author: Nitesh Kumar
     * Rake reports
     * Created date:1-1-2020 To 3-1-2020
     */
    Route::group(['namespace' => 'reports', 'prefix' => 'reports', 'as' => 'reports.'], function () {

        Route::group(['prefix' => 'baazitds', 'as' => 'baazitds.'], function () {
            Route::get('Search', 'BaazitdsSearchController@index')->name('index');
            Route::post('Search', 'BaazitdsSearchController@BaaziTdsSearch')->name('BaaziTdsSearch');
            Route::get('exportExcel', 'BaazitdsSearchController@exportExcel')->name('exportExcel');
        });

        Route::group(['prefix' => 'rake-report', 'as' => 'rake-report.'], function () {
            Route::get('/', 'RakeReportController@index')->name('index');
            Route::post('exportExcel', 'RakeReportController@exportExcel')->name('exportExcel');
        });

        /* daily stats report start */
        Route::group(['prefix' => 'dailystats', 'as' => 'dailystats.'], function () {
            Route::match(['get', 'post'], '/', 'DailyReportController@index')->name('index');
            Route::match(['get', 'post'], 'excel', 'DailyReportController@excelExportDailyReport');
            Route::get('/exportpdf/pdf', 'DailyReportController@export_daily_pdf');
            Route::post('receipientmaillist', 'DailyReportController@ReceipientMailList');
        });
        /*daily stats report end*/

        Route::group(['prefix'=>'coinsummary', 'as'=>'coinsummary.'], function(){
            Route::get('/', 'CoinsSummaryController@index')->name('index');
            Route::post('/', 'CoinsSummaryController@coinsSummary')->name('coinsSummary');
            Route::get('exportExcel','CoinsSummaryController@exportExcel')->name('exportExcel');
        });

        /*withdraw report start*/
        /**
         * Author: Basanta Swain
         * Purpose: Withdraw Approve and reject.
         * Created Date: 30/01/2020
         */
        Route::group(['prefix' => 'withdraw', 'as' => 'withdraw.'], function () {
            Route::get('/', 'WithdrawReportController@index')->name('index');
            Route::post('/', 'WithdrawReportController@index')->name('search');
            Route::post('/userFlagUpdate', 'WithdrawReportController@userFlagUpdate')->name('userFlagUpdate');
            Route::get('/getExcelExport','WithdrawReportController@withdrawExcelExport')->name('getExcelExport');
            Route::post('/getUserFirstWitStatus','WithdrawReportController@getUserFirstWithdrawStatus')->name('getUserFirstWitStatus');
            Route::post('/get_user_win','WithdrawReportController@getUserWin')->name('getUserFiget_user_winrstWitStatus');
            Route::post('/get_private_table','WithdrawReportController@privateTableStatus')->name('get_private_table');
            // Route::get('/update_payu_status','WithdrawReportController@payuManuallyWebhookCall')->name('update_payu_status_db');
            // Route::get('/update_cashfree_status','WithdrawReportController@cashfreeManuallyWebhookCall')->name('update_cashfree_status_db');

            Route::group(['prefix'=>'action', 'as'=>'action.'], function(){
                Route::middleware('canAccess:view,withdrawal_normal_approve')->post('/normal_approve', 'WithdrawReportController@withdrawNormalApprove')->name('normal_approve');
                Route::middleware('canAccess:view,withdrawal_normal_reject')->post('/normal_reject', 'WithdrawReportController@withdrawNormalReject')->name('normal_reject');
                Route::middleware('canAccess:view,withdrawal_cashfree_approve')->post('/withdrawal_cashfree_approve', 'WithdrawReportController@withdrawCashfreeApprove')->name('withdrawal_cashfree_approve');
                Route::middleware('canAccess:view,withdrawal_cashfree_reject')->post('/withdrawal_cashfree_reject', 'WithdrawReportController@withdrawCashfreeReject')->name('withdrawal_cashfree_reject');

app/Http/Controllers/bo/settings/reason/ManageReasonCategoryController.php
<?php

namespace App\Http\Controllers\bo\settings\reason;

use App\Http\Controllers\bo\BaseController;
use Illuminate\Http\Request;
use App\Models\ReasonCategory;
use DB;
use Auth;

class ManageReasonCategoryController extends BaseController
{
    public function index(){
    	return view('bo.views.settings.reason.category.index',['dataSets' => ReasonCategory::orderBy('REASON_CATEGORY_ID','DESC')->get()]);
    }

    public function store(Request $request){

    	$request->validate([
    		'category_name' => 'required|unique:reason_category,reason_category_name|string',
    		'category_description' => 'nullable|string'
    	]);

    	$data['reason_category_name'] = $request->category_name;
    	$data['reason_category_description'] = $request->category_description;
    	$data['created_by'] = Auth::user()->username;
    	$data['updated_by'] = Auth::user()->username;
    	$data['created_date'] = date('Y-m-d H:i:s');

    	if(ReasonCategory::create($data)){
    		return redirect()->back()->with('success', "Reason Category Created Successfully.");
    	}
        else{
            return redirect()->back()->with('danger', "Failed To Create Reason Category.");
        }

    }

    public function show($id){
    	return ReasonCategory::findOrFail($id);
    }	

    public function update(Request $request, $id){

		if($request->has('action') && $request->action=='toggleStatus'){
    		$category = ReasonCategory::where('REASON_CATEGORY_ID', $id)->update(
    			[
    				'STATUS' => $request->value == "true" ? 1 : 0, 
    				'updated_by'=>Auth::user()->username, 
    				'update_date'=>date('Y-m-d H:i:s')
    			]
    		);
    		return response()->json($category);
    	}

        $category = ReasonCategory::find($id); 

    	$request->validate([
    		'category_name' => 'required|unique:reason_category,reason_category_name,'.$category->REASON_CATEGORY_ID.',REASON_CATEGORY_ID|string',
    		'category_description' => 'nullable|string'
    	]);

    	$category = ReasonCategory::find($id);

    	$category->reason_category_name = $request->category_name;
    	$category->reason_category_description = $request->category_description;
    	$category->updated_by = Auth::user()->username;
    	$category->update_date = date('Y-m-d H:i:s');
    	


    	if($category->save()){
    		return redirect()->back()->with('info', "Reason Category Updated.");
    	}
    	else{
    		return redirect()->back()->with('danger', "Failed To Updatde Reason Category.");
    	}

    }
}

app/Http/Controllers/bo/settings/reason/ManageReasonController.php
<?php

namespace App\Http\Controllers\bo\settings\reason;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use\App\Models\ReasonCategory;
use\App\Models\ActionReason;
use DB;
use Auth;

class ManageReasonController extends Controller
{
    public function index(){

    	$categories = ReasonCategory::active()->get();
        
    	return view('bo.views.settings.reason.action.index',['activeCategories' => $categories, 'dataSets' => ActionReason::notDeleted()->orderBy('ACTIONS_REASONS_ID','DESC')->get()]);
    }

    public function store(Request $request){

    	$request->validate([
    		'reason_category_id'=>'required',
    		'actions_reason'=>'required'
    	]);

    	$data['reason_category_id'] = implode(',',$request->reason_category_id);
    	$data['actions_reason'] = $request->actions_reason;
    	$data['actions_reason_description'] = $request->actions_reason_description;
    	$data['updated_by'] = $data['created_by'] = Auth::user()->username;
    	$data['created_date'] = $data['update_date'] = date('Y-m-d H:i:s'); 
    
    	if(ActionReason::create($data)){
    		return redirect()->back()->with('success', "Reason Created Successfully.");
    	}
    	else{
    		return redirect()->back()->with('danger', "Failed To Create Reason.");
    	}
    }

    public function update(Request $request, $id){

        

    	$actionReason = ActionReason::find($id);
    	$actionReason->updated_by=Auth::user()->username;
    	$actionReason->update_date=date('Y-m-d H:i:s');

    	if($request->has('action') && $request->action='toggleStatus'){     		
    		if($request->value!='true' && $request->value!='false'){
    			$actionReason->status=$request->value;
    			$actionReason->save(); 
    			return redirect()->back()->with('success','Reason Deleted Successfully.');
    		}
    		else{
    			$actionReason->status=($request->value=='true'? 1 : 0);
    			$actionReason->save();
    			return response()->json($actionReason);
    		}
    	}

    	$actionReason->actions_reason = $request->actions_reason;
    	$actionReason->actions_reason_description = $request->actions_reason_description;
    	$actionReason->reason_category_id = implode(',',$request->reason_category_id);

        if($actionReason->save()){
            return redirect()->back()->with('success', "Reason Updated Successfully.");
        }
        else{
            return redirect()->back()->with('danger', "Failed To Update Reason.");
        }

    }

    public function show($id){
    	return ActionReason::findOrFail($id);
    }

}

resources/views/bo/views/settings/reason/category/index.blade.php
@extends('bo.layouts.master')

@section('title', "Manage Category | PB BO")

@section('pre_css')
<style type="text/css">
    .mandetory{ color:red;font-weight: bold; }
</style>
    
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item">
                                <a>Settings </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a>Manage Category</a>
                            </li>
                        </ol>
                    </div>
                    <h4 class="page-title">Reasons Category</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-3">
                            <div class="col-sm-4">
                                <h5 class="font-18">
                                    Manage Reason's Category
                                </h5>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-right">
                                    <a
                                        href="#"
                                        class="btn btn-success waves-effect waves-light"
                                        data-toggle="modal"
                                        title="Edit"
                                        data-target="#AddrolemyModal"
                                    >
                                        <i class="fa fa-plus mr-1"></i>Add
                                        Reason's Category
                                    </a>
                                </div>
                            </div>
                            <!-- end col-->
                        </div>
                        <table
                            class="table table-centered table-striped dt-responsive nowrap w-100"
                            id="basic-datatable"
                        >
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Category Name</th>
                                    <th>Category Description</th>
                                    <th>Added By</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $sNo = 1; ?>
                                @if(!empty($dataSets))

                                    @foreach($dataSets as $dataSet)
                                        <tr>
                                            <td>{{ $sNo++ }}</td>
                                            <td>{{ $dataSet->REASON_CATEGORY_NAME }}</td>
                                            <td class="ellipsisWrapper">
                                                <div class="ellipsis">
                                                    {{ $dataSet->REASON_CATEGORY_DESCRIPTION }}
                                                </div>    
                                            </td>
                                            <td>{{ $dataSet->CREATED_BY }}</td>
                                            <td class="text-center">
                                                <a
                                                    id="{{ $dataSet->REASON_CATEGORY_ID }}"
                                                    class="action-icon font-14 tooltips"  
                                                    data-plugin="tippy"
                                                    style="cursor:pointer;"
                                                    data-tippy-interactive="true"
                                                    onClick="show(this.id);"
                                                > <span class="tooltiptext">Edit</span>
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach    
                                @endif
                            </tbody>
                        </table>
                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card-->
            </div>
            <!-- end col -->
        </div>
    </div>
</div>
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content bg-transparent shadow-none position-relative">
            <!---<div class="d-flex justify-content-center hv_center">
            <div class="spinner-border" role="status"></div>
            </div>
            <div class="card  blureffect">--->
            <div class="card">
                <div class="card-header bg-secondary py-3 text-white">
                    <div class="card-widgets">
                        <a href="#" data-dismiss="modal">
                            <i class="mdi mdi-close"></i>
                        </a>
                    </div>
                    <h5 class="card-title mb-0 text-white font-18">
                        Edit Reason's Category
                    </h5>
                </div>
                <div class="card-body position-relative">
                    <form id="categoryEditForm" method="post" >
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="name">Category Name: <span class="mandetory">*</span></label>
                            <input
                                type="text"
                                class="form-control maxlengtherror"
                                name="category_name"
                                 maxlength="50"
                                placeholder=""
                                required
                            />
                        </div>
                        <div class="form-group mb-3">
                            <label>Category Description:</label>
                            <textarea
                                class="form-control maxlengtherror"
                                maxlength="225"
                                name="category_description"
                                rows="5"
                            ></textarea>
                        </div>
                        <div class="text-right">
                            <button
                                type="submit"
                                class="btn btn-warning waves-effect waves-light "
                            >
                                <i class="far fa-edit mr-1"></i> Update
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="AddrolemyModal">
    <div class="modal-dialog">
        <div class="modal-content bg-transparent shadow-none position-relative">
            <!----<div class="d-flex justify-content-center hv_center">
            <div class="spinner-border" role="status"></div>
            </div>
            <div class="card  blureffect">--->
            <div class="card ">
                <div class="card-header bg-dark py-3 text-white">
                    <div class="card-widgets">
                        <a href="#" data-dismiss="modal">
                            <i class="mdi mdi-close"></i>
                        </a>
                    </div>
                    <h5 class="card-title mb-0 text-white font-18">
                        Add Reason's Category
                    </h5>
                </div>
                <div class="card-body">
                    <form id="categoryForm" method="post" action="{{ route('settings.reason-category.store') }}" name="categoryForm" data-parsley-validate="">
                        @csrf
                        <div class="form-group">
                            <label for="name">Category Name: <span class="mandetory">*</span></label>
                            <input
                                type="text"
                                class="form-control maxlengtherror"
                                maxlength="50"
                                value="{{ old('category_name') }}"
                                name="category_name"
                            />
                            @error('category_name')
                            <label id="category_name-error" class="error" for="category_name">{{ $message }}</label>
                            @enderror
                        </div>
                        <div class="form-group mb-3">
                            <label>Category Description:</label>
                            <textarea
                                name="category_description"
                                rows="5"
                                
                                class="form-control maxlengtherror"
                                maxlength="225"
                            ></textarea>
                        </div>
                        <div class="text-right" id="submitButtonWrap">
                            <button
                                type="submit"
                                class="btn btn-success waves-effect waves-light"
                            >
                                <i class="fa fa-save mr-1"></i> Save
                            </button>

                            <!-- <button
                                type="button"
                                class="btn btn-dark waves-effect waves-light ml-2"
                                onclick="Custombox.close();"
                            >
                                <i class="mdi mdi-replay mr-1"></i>Reset
                            </button> -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')
<script src="{{asset('assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js')}}"></script>
<script type="text/javascript">

    $(document).ready(function(){
        var validRules = {
            rules:{
                category_name:{
                    required : true,
                    pattern :   /^[a-zA-Z0-9-_'.$1\n& ]+$/
                },
                category_description:{
                    pattern :   /^[a-zA-Z0-9-_'.$1\n& ]+$/
                }
            }
        };
        
        $("#categoryForm").validate(validRules);
        $("#categoryEditForm").validate(validRules);

        show = (id) => {
            $.ajax({
                url :`${window.pageData.baseUrl}/settings/reason-category/${id}`,
                dataType : 'JSON',
                success : function(data){
                    $('#categoryEditForm input[name="category_name"]').val('').val(data.REASON_CATEGORY_NAME);
                    $('#categoryEditForm textarea[name="category_description"]').val('').val(data.REASON_CATEGORY_DESCRIPTION);
                    $('#categoryEditForm').attr('action',`${window.pageData.baseUrl}/settings/reason-category/${id}`);
                    $('#myModal').modal('show');
                }  
            });
        }

        toggleStatus = (target_id, id) => {
            $.ajax({
                url :`${window.pageData.baseUrl}/settings/reason-category/${id}`,
                type:'POST',
                data:{
                    action : 'toggleStatus',
                    value  :  $('#'+target_id).prop('checked'),
                    _method : 'PATCH'
                },
                success : ()=> {
                   $.NotificationApp.send("Well Done", ($('#'+target_id).prop('checked')?'Status <i><b>Enabled</b></i> Successfully.':'Status <i><b>Disabled</b></i> Successfully.'), 'top-right', '#3b98b5', 'success');
                }
            });
        }

        $("#categoryForm").submit(() => {
            let loaderBtn = `<button  class="btn btn-primary formActionButton mr-1" id="confirm-hide-excel" type="button" disabled="disabled">
                    <span class="spinner-border spinner-border-sm mr-1" role="status" aria-hidden="true"></span>
                    Loading...
                  </button>`;
            if($("#categoryForm").valid()){
                $("#submitButtonWrap").html(loaderBtn);
            }
        });

    });

    @error('category_name')
        $.NotificationApp.send("Error", 'This Category Already Exists.', 'top-right', '#3b98b5', 'warning');
    @enderror
    
</script>
@endsection